### ISSUE TITLE
Clicking import tracking parameters and cancelling causes idTracker to crash

### ISSUE THREAD

**Issue by dmyersturnbull** [alperezescudero/idTracker#11]
On Mac OS X 10.11.4 and MATLAB R2016a with idTracker beta. To reproduce:
1. Call `idTracker('../..', 'test.mp4')`
2. Click "import tracking parameters"
3. Click cancel

Full output:

```
>> idTracker('../..', 'test.mp4')
1,
Guarning!
Starting parallel pool (parpool) using the 'local' profile ... connected to 2 workers.
Error using dir
Invalid path. The path must not contain a null character.

Error in panel_identitracking>importaparametros (line 844)
if ~isempty(dir([directorio 'segm' filesep 'datosegm.mat']))


Error in panel_identitracking>@(uno,dos)importaparametros(uno,dos,h) (line 261)
    set(h.menu_import,'Callback',@(uno,dos) importaparametros(uno,dos,h))


Error using uiwait (line 81)
Error while evaluating Menu Callback

Error using panel_identitracking (line 321)
Control panel closed by the user

Error in idTracker (line 285)
            [datosegm,h_panel]=panel_identitracking(datosegm);
```

**Comment by ahof1704** [comment]
It is a real bug! 
I just made a fix for it. It is working now, but as it is not a major problem, I would like to hold for a while and release it later, because there are other groups testing this current version.  

If this is really important for you now, I can send you the newest version. 

Please, keep us posted about how it is going there! =)

Antonio.

**Comment by dmyersturnbull** [comment]
Great, glad to hear it's fixed! Perhaps you could commit these changes to a new "Dev" branch? Then you can just merge them into Beta when you're ready to release.

**Comment by ahof1704** [comment]
Done!

It is in my branch now.

Thanks.
Antonio.
ᐧ

On Wed, Jun 15, 2016 at 11:01 AM, Douglas Myers-Turnbull <
notifications@github.com> wrote:

> Great, glad to hear it's fixed! Perhaps you could commit these changes to
> a new "Dev" branch? Then you can just merge them into Beta when you're
> ready to release.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/idTracker/idTracker/issues/11#issuecomment-226215073,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHukxA6F5OOwyAiEQJ4I97T1xoLvXDRSks5qMBO3gaJpZM4I16CP
> .

## 

Antonio Henrique de Oliveira Fonseca
antonio.fonseca@yale.edu
Automation, Instrumentation and Robotics Engineering - UFABC / Laurentian
University.
Post-Graduate Associate in Comparative Medicine - Yale School of Medicine
