### ISSUE TITLE
idTracker is not compatible with newer versions of Matlab

### ISSUE THREAD

**Issue by alperezescudero** [alperezescudero/idTracker#3]
Last version compatible is r2014a. Incompatibilites include issues with the graphical interface, and with parallel toolbox.

**Comment by dmyersturnbull** [comment]
Is there any available workaround?
I don't know MATLAB (yet), but I may be available to lend a hand.

**Comment by alperezescudero** [comment]
This issue was solved by Antonio. A version compatible with Matlab 2016 is in branch Beta.
